//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReminderServiceEmailSender_Console.WebAPIService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebAPIService.IAPIService")]
    public interface IAPIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/DoWork", ReplyAction="http://tempuri.org/IAPIService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/DoWork", ReplyAction="http://tempuri.org/IAPIService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetReminders", ReplyAction="http://tempuri.org/IAPIService/GetRemindersResponse")]
        string GetReminders();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/GetReminders", ReplyAction="http://tempuri.org/IAPIService/GetRemindersResponse")]
        System.Threading.Tasks.Task<string> GetRemindersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/DeleteReminder", ReplyAction="http://tempuri.org/IAPIService/DeleteReminderResponse")]
        void DeleteReminder(System.Guid ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAPIService/DeleteReminder", ReplyAction="http://tempuri.org/IAPIService/DeleteReminderResponse")]
        System.Threading.Tasks.Task DeleteReminderAsync(System.Guid ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAPIServiceChannel : ReminderServiceEmailSender_Console.WebAPIService.IAPIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APIServiceClient : System.ServiceModel.ClientBase<ReminderServiceEmailSender_Console.WebAPIService.IAPIService>, ReminderServiceEmailSender_Console.WebAPIService.IAPIService {
        
        public APIServiceClient() {
        }
        
        public APIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public string GetReminders() {
            return base.Channel.GetReminders();
        }
        
        public System.Threading.Tasks.Task<string> GetRemindersAsync() {
            return base.Channel.GetRemindersAsync();
        }
        
        public void DeleteReminder(System.Guid ID) {
            base.Channel.DeleteReminder(ID);
        }
        
        public System.Threading.Tasks.Task DeleteReminderAsync(System.Guid ID) {
            return base.Channel.DeleteReminderAsync(ID);
        }
    }
}
